apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler/kubeconfig.yaml
    - --authorization-kubeconfig=/etc/kubernetes/scheduler/kubeconfig.yaml
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler/kubeconfig.yaml
    - --leader-elect=true
    image: k8s.gcr.io/kube-scheduler:v<%= node[:kubernetes].fetch(:version) %>
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
      - mountPath: /etc/kubernetes/scheduler
        name: etc-scheduler
        readOnly: true
      - mountPath: /etc/ssl/self/k8s-kube-scheduler
        name: certs
        readOnly: true

  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler
      type: DirectoryOrCreate
    name: etc-scheduler
  - hostPath:
      path: /etc/ssl/self/k8s-kube-scheduler
      type: DirectoryOrCreate
    name: certs

status: {}
