apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/ssl/self/k8s-node/trust.pem
    server: 'https://<%= node[:kubernetes].fetch(:cluster_name) %>.k8s-control.nkmi.me:6443'
  name: '<%= node[:kubernetes].fetch(:cluster_name) %>'
contexts:
- context:
    cluster: '<%= node[:kubernetes].fetch(:cluster_name) %>'
    user: 'system:node:<%= node[:hostname] %>'
  name: 'system:node:<%= node[:hostname] %>@<%= node[:kubernetes].fetch(:cluster_name) %>'
current-context: 'system:node:<%= node[:hostname] %>@<%= node[:kubernetes].fetch(:cluster_name) %>'
kind: Config
preferences: {}
users:
- name: 'system:node:<%= node[:hostname] %>'
  user:
    client-certificate: /etc/ssl/self/k8s-node/fullchain.pem
    client-key: /etc/ssl/self/k8s-node/key.pem
