apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration

extenders:
<%- if node[:kubernetes][:scheduler][:topolvm] -%>
  - urlPrefix: "http://127.0.0.1:9251"
    filterVerb: "predicate"
    prioritizeVerb: "prioritize"
    nodeCacheCapable: false
    weight: 1
    managedResources:
      - name: "topolvm.cybozu.com/capacity"
        ignoredByScheduler: true
<%- end -%>

clientConnection:
  kubeconfig: /etc/kubernetes/scheduler/kubeconfig.yaml
