apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/ssl/self/k8s-kube-controller-manager/trust.pem
    server: 'https://<%= node[:kubernetes].fetch(:cluster_name) %>.k8s-control.nkmi.me:6443'
  name: '<%= node[:kubernetes].fetch(:cluster_name) %>'
contexts:
- context:
    cluster: '<%= node[:kubernetes].fetch(:cluster_name) %>'
    user: 'system:kube-controller-manager'
  name: 'system:kube-controller-manager@<%= node[:kubernetes].fetch(:cluster_name) %>'
current-context: 'system:kube-controller-manager@<%= node[:kubernetes].fetch(:cluster_name) %>'
kind: Config
preferences: {}
users:
- name: 'system:kube-controller-manager'
  user:
    client-certificate: /etc/ssl/self/k8s-kube-controller-manager/fullchain.pem
    client-key: /etc/ssl/self/k8s-kube-controller-manager/key.pem
